// Auto-generated by the postman-to-k6 converter

import "./libs/shim/core.js";
import "./libs/shim/urijs.js";

export let options = { maxRedirects: 4 };

const Request = Symbol.for("request");
postman[Symbol.for("initial")]({
  options,
  environment: {
    jwtToken: "",
    guid: "",
    springBootSecurityUrl: "http://localhost:8888/springbootsecurity",
    usernameSpringBoot: "user@gmail.com",
    passwordSpringBoot: "1234"
  }
});

export default function() {
  postman[Request]({
    name: "Login",
    id: "01bb74e8-dcbc-45b0-a39a-b157fdffc57a",
    method: "POST",
    address: "{{springBootSecurityUrl}}/dispatcher/api/authentication",
    data:
      '{\n    "username": "{{usernameSpringBoot}}",\n    "password": {{passwordSpringBoot}}\n}',
    headers: {
      "Content-Type": "application/json",
      Accept: "application/json"
    },
    post(response) {
      pm.test("Status code is 200", function() {
        pm.response.to.have.status(200);
        var jsonData = pm.response.json();
        var jwtToken = jsonData.data.jwt;
        var guid = jsonData.data.uid;
        console.log("Jwt token: " + jwtToken);
        pm.environment.set("jwtToken", jwtToken);
        pm.environment.set("guid", guid);
      });
    }
  });

  postman[Request]({
    name: "Logout",
    id: "1f0e2ac8-38c4-4fc1-9f61-2eda72671a8e",
    method: "DELETE",
    address:
      "{{springBootSecurityUrl}}/dispatcher/api/authentication/{{guid}}?username=user@gmail.com",
    post(response) {
      pm.test("Status code is 200", function() {
        pm.response.to.have.status(200);
        var jsonData = pm.response.json();
        var response = jsonData.data;
        if (response === null) {
          console.log(
            "Removing the Authorization token from the global scope.."
          );
          pm.environment.set("jwtToken", "");
        }
      });
    },
    auth(config, Var) {
      config.headers.Authorization = `Bearer ${pm[Var]("jwtToken")}`;
    }
  });

  postman[Request]({
    name: "Get all users",
    id: "7aca99f0-9e2b-40bf-a893-eef5d524a1a8",
    method: "GET",
    address: "{{springBootSecurityUrl}}/dispatcher/api/user/all"
  });
}
